### ISSUE TITLE
[Django Error] ' XXX Serializer' object has no attribute 'error'

### ISSUE THREAD

**Issue by stbaker517** [skkuse/2022fall_41class_team9#6]
DB의 serializer를 import하여 사용할 때

serializer.is_valid() == False일 때 발생.

error 문구 :   XXX Serializer' object has no attribute 'error'

**Comment by metishonora** [comment]
이건 아마 migration error로 생각되네요. fix/db의 README를 확인해보시고, 여전히 오류가 있다면 다시 멘션해주세요. @stbaker517
