### ISSUE TITLE
Problem model - tag 이슈

### ISSUE THREAD

**Issue by stbaker517** [skkuse/2022fall_41class_team9#7]
`class Problem(models.Model):
    prob_id = models.IntegerField(primary_key=True)
    course_id = models.ForeignKey('Course', on_delete=models.CASCADE)
    writer = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    tag = models.TextField()
    description = models.TextField()
    constraint = models.TextField()
    answer_code = models.TextField()
    skeleton = models.TextField()
    max_submission = models.IntegerField()
    deadline = models.DateField()
    tc_open = models.TextField()
    tc_close = models.TextField()`

태그를 보시면 한가지 태그만 등록이 가능합니다. json string을 의도하고 넣으신 건가요?

**Comment by metishonora** [comment]
원래는 ArrayField로 작업하려 했는데 이 필드가 postgresql이 필요하네요. sqlite3에서는 따로 처리할 방법이 없는 것 같습니다. JSON이나 문자열 형식으로 DB에는 입력하시고, 백엔드에서 파싱하여 사용해야할 것 같습니다.

**Comment by metishonora** [comment]
의도한 것은 tag = "tagA,tagB,tacC,...,tacZ"로 db에 저장하고, 백엔드에선 이것을 파싱 후 알아서 관리하는 것입니다.
